BEGIN;

-- Create ENUM type for user roles (only if not exists)
DO $$
    BEGIN
        CREATE TYPE user_role AS ENUM ('ADMIN', 'CREATOR', 'CUSTOMER');
    EXCEPTION
        WHEN duplicate_object THEN null;
    END $$;

-- Create tables
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       hashed_password VARCHAR(255) NOT NULL,
                       role user_role NOT NULL,
                       username VARCHAR(255) NOT NULL
);

CREATE TABLE courses (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         creator_id BIGINT NOT NULL,
                         description VARCHAR(255),
                         price DOUBLE PRECISION NOT NULL,
                         title VARCHAR(255) NOT NULL
);

CREATE TABLE purchases (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           amount_paid DOUBLE PRECISION NOT NULL,
                           course_id BIGINT NOT NULL,
                           customer_id BIGINT NOT NULL,
                           purchase_date DATE NOT NULL
);

-- Foreign key constraints
ALTER TABLE courses
    ADD CONSTRAINT fk_courses_creator FOREIGN KEY (creator_id) REFERENCES users(id);

ALTER TABLE purchases
    ADD CONSTRAINT fk_purchases_course FOREIGN KEY (course_id) REFERENCES courses(id);

ALTER TABLE purchases
    ADD CONSTRAINT fk_purchases_customer FOREIGN KEY (customer_id) REFERENCES users(id);

COMMIT;





