BEGIN;

-- Create ENUM type for user roles (only if not exists)
DO $$
    BEGIN
        CREATE TYPE user_role AS ENUM ('ADMIN', 'CREATOR', 'CUSTOMER');
    EXCEPTION
        WHEN duplicate_object THEN null;
    END $$;

    CREATE TABLE courses
    (
        id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        title       VARCHAR(255)                            NOT NULL,
        description VARCHAR(255),
        price       DOUBLE PRECISION                        NOT NULL,
        creator_id  BIGINT                                  NOT NULL,
        CONSTRAINT pk_courses PRIMARY KEY (id)
    );

    CREATE TABLE purchases
    (
        id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        customer_id   BIGINT                                  NOT NULL,
        course_id     BIGINT                                  NOT NULL,
        amount_paid   DOUBLE PRECISION                        NOT NULL,
        purchase_date date                                    NOT NULL,
        CONSTRAINT pk_purchases PRIMARY KEY (id)
    );

    CREATE TABLE users
    (
        id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        username        VARCHAR(255)                            NOT NULL,
        email           VARCHAR(255)                            NOT NULL,
        hashed_password VARCHAR(255)                            NOT NULL,
        authority       VARCHAR(255),
        CONSTRAINT pk_users PRIMARY KEY (id)
    );

    ALTER TABLE users
        ADD CONSTRAINT uc_users_email UNIQUE (email);

    ALTER TABLE courses
        ADD CONSTRAINT FK_COURSES_ON_CREATOR FOREIGN KEY (creator_id) REFERENCES users (id);

    ALTER TABLE purchases
        ADD CONSTRAINT FK_PURCHASES_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);

    ALTER TABLE purchases
        ADD CONSTRAINT FK_PURCHASES_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES users (id);


COMMIT;





